# Generated by Django 5.0 on 2025-10-01 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellido", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("documento", models.CharField(max_length=20, unique=True)),
                (
                    "legajo",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("fecha_nacimiento", models.DateField()),
                ("cv", models.FileField(blank=True, null=True, upload_to="cvs/")),
                ("cv_confirmado", models.BooleanField(default=False)),
                ("cv_fecha_confirmacion", models.DateField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Docente",
                "verbose_name_plural": "Docentes",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("I", "Nivel I"),
                            ("II", "Nivel II"),
                            ("III", "Nivel III"),
                            ("IV", "Nivel IV"),
                            ("V", "Nivel V"),
                            ("VI", "Nivel VI"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "puntaje",
                    models.PositiveIntegerField(help_text="Puntaje de la asignatura"),
                ),
                ("horas_semanales", models.PositiveIntegerField()),
                ("horas_totales", models.PositiveIntegerField()),
                ("es_obligatoria", models.BooleanField(default=True)),
                (
                    "forma_dictado",
                    models.CharField(
                        choices=[
                            ("anual", "Anual"),
                            ("1c", "1er Cuatrimestre"),
                            ("2c", "2do Cuatrimestre"),
                        ],
                        max_length=10,
                    ),
                ),
                ("areas", models.ManyToManyField(blank=True, to="core.area")),
                ("bloques", models.ManyToManyField(blank=True, to="core.bloque")),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.carrera"
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignatura",
                "verbose_name_plural": "Asignaturas",
                "ordering": ["carrera", "nivel", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Correo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("es_principal", models.BooleanField(default=False)),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correos",
                        to="planta_docente.docente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correo Electrónico",
                "verbose_name_plural": "Correos Electrónicos",
            },
        ),
        migrations.CreateModel(
            name="Resolucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50)),
                ("anio", models.PositiveIntegerField()),
                (
                    "objeto",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("baja", "Baja"),
                            ("licencia", "Licencia"),
                            ("prorroga", "Prórroga"),
                            ("cambio_dedicacion", "Cambio de Dedicación"),
                            ("otro", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("decano", "Decano"),
                            ("rector", "Rector"),
                            ("consejo_academico", "Consejo Académico"),
                            ("consejo_superior", "Consejo Superior"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fecha_emision", models.DateField()),
                (
                    "archivo_digital",
                    models.FileField(blank=True, null=True, upload_to="resoluciones/"),
                ),
                (
                    "detalle_funciones_sustantivas",
                    models.TextField(
                        blank=True,
                        help_text="Requerido para cargos con menos de 4 horas semanales",
                        null=True,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Resolución",
                "verbose_name_plural": "Resoluciones",
                "ordering": ["-anio", "-numero"],
                "unique_together": {("numero", "anio", "origen")},
            },
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comision",
                    models.CharField(
                        default="1", help_text="Número de comisión", max_length=20
                    ),
                ),
                (
                    "caracter",
                    models.CharField(
                        choices=[
                            ("ordinario", "Ordinario"),
                            ("regular", "Regular"),
                            ("interino", "Interino"),
                            ("extraordinario", "Extraordinario"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("profesor_titular", "Profesor Titular"),
                            ("profesor_asociado", "Profesor Asociado"),
                            ("profesor_adjunto", "Profesor Adjunto"),
                            ("jefe_trabajos_practicos", "Jefe de Trabajos Prácticos"),
                            ("ayudante_diplomado", "Ayudante Diplomado"),
                            ("ayudante_estudiante", "Ayudante Estudiante"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "dedicacion",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("semiexclusiva", "Semiexclusiva"),
                            ("exclusiva", "Exclusiva"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cantidad_horas", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("licencia", "Licencia"),
                            ("baja", "Baja"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_final", models.DateField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField()),
                ("observaciones", models.TextField(blank=True)),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planta_docente.asignatura",
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos",
                        to="planta_docente.docente",
                    ),
                ),
                (
                    "resolucion_alta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="planta_docente.resolucion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
