# Generated by Django 5.0 on 2025-10-01 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equivalencias', '0001_initial'),
        ('planta_docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal', max_length=7)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado_general', models.CharField(choices=[('en_proceso', 'En Proceso'), ('plan_aprobado', 'Plan Aprobado'), ('en_ejecucion', 'En Ejecución'), ('informe_presentado', 'Informe Presentado'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='en_proceso', max_length=30)),
                ('tema', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('supervisor', models.CharField(blank=True, help_text='Nombre del supervisor. Puede ser externo', max_length=255)),
                ('empresa_institucion', models.CharField(blank=True, max_length=255)),
                ('plan_trabajo', models.FileField(upload_to='ps/planes/')),
                ('fecha_aprobacion_plan', models.DateField(blank=True, null=True)),
                ('informe_final', models.FileField(blank=True, null=True, upload_to='ps/informes/')),
                ('fecha_presentacion_informe', models.DateField(blank=True, null=True)),
                ('fecha_completada', models.DateField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equivalencias.estudiante')),
                ('etiquetas', models.ManyToManyField(blank=True, to='practica_supervisada.etiquetaps')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tutor_ps', to='planta_docente.docente')),
            ],
            options={
                'verbose_name': 'Práctica Supervisada',
                'verbose_name_plural': 'Prácticas Supervisadas',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='JuradoPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_externo', models.CharField(blank=True, help_text='Nombre completo si es jurado externo', max_length=255, null=True)),
                ('institucion_externa', models.CharField(blank=True, max_length=255)),
                ('estado_dictamen_plan', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('aprobado_observaciones', 'Aprobado con Observaciones'), ('denegado', 'Denegado')], default='pendiente', max_length=30)),
                ('observaciones_plan', models.TextField(blank=True)),
                ('fecha_dictamen_plan', models.DateField(blank=True, null=True)),
                ('estado_dictamen_informe', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('aprobado_observaciones', 'Aprobado con Observaciones'), ('denegado', 'Denegado')], default='pendiente', max_length=30)),
                ('observaciones_informe', models.TextField(blank=True)),
                ('fecha_dictamen_informe', models.DateField(blank=True, null=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta_docente.docente')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurados', to='practica_supervisada.psolicitud')),
            ],
            options={
                'verbose_name': 'Jurado',
                'verbose_name_plural': 'Jurados',
            },
        ),
    ]
