# Generated by Django 5.0 on 2025-10-01 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('planta_docente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignaturaParaEquivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_equivalencia', to='planta_docente.asignatura')),
                ('docente_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='planta_docente.docente')),
            ],
            options={
                'verbose_name': 'Asignatura para Equivalencia',
                'verbose_name_plural': 'Asignaturas para Equivalencia',
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_asignatura', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada al Docente'), ('aprobada', 'Aprobada'), ('aprobada_pc', 'Aprobada con Programa Complementario'), ('denegada', 'Denegada')], default='pendiente', max_length=50)),
                ('detalle_pc', models.TextField(blank=True, help_text='Detallar qué debe cubrir el programa complementario')),
                ('fecha_dictamen', models.DateField(blank=True, null=True)),
                ('observaciones_docente', models.TextField(blank=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equivalencias.asignaturaparaequivalencia')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitud',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email_estudiante', models.EmailField(blank=True, max_length=254, null=True)),
                ('dni_pasaporte', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.carrera')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudEquivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('estado_general', models.CharField(choices=[('proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='proceso', max_length=20)),
                ('acta_firmada', models.FileField(blank=True, null=True, upload_to='actas_equivalencia/')),
                ('fecha_completada', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('asignaturas', models.ManyToManyField(through='equivalencias.DetalleSolicitud', to='equivalencias.asignaturaparaequivalencia')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equivalencias.estudiante')),
            ],
            options={
                'verbose_name': 'Solicitud de Equivalencia',
                'verbose_name_plural': 'Solicitudes de Equivalencia',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos_equivalencia/%Y/%m/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equivalencias.solicitudequivalencia')),
            ],
            options={
                'verbose_name': 'Documento Adjunto',
                'verbose_name_plural': 'Documentos Adjuntos',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equivalencias.solicitudequivalencia'),
        ),
        migrations.AlterUniqueTogether(
            name='detallesolicitud',
            unique_together={('solicitud', 'asignatura')},
        ),
    ]
