# Nombre del workflow que aparecerá en la pestaña "Actions" de GitHub
name: CI de Django

# Define cuándo se debe ejecutar este workflow
on:
  # Se ejecuta en cada push a la rama "main"
  push:
    branches: [ "main" ]
  # También se ejecuta en cada Pull Request que apunte a la rama "main"
  pull_request:
    branches: [ "main" ]

# Define los trabajos (jobs) que se ejecutarán
jobs:
  # Nombre del trabajo, puedes llamarlo como quieras (ej. "build", "test")
  build:
    # El tipo de máquina virtual donde se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Los pasos que componen el trabajo
    steps:
      # 1. Clona tu repositorio en la máquina virtual
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configura el entorno de Python
      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # Habilita el caché para las dependencias de pip para acelerar futuras ejecuciones
          cache: 'pip'

      # 3. Instala las dependencias del proyecto
      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # 4. Ejecuta el linter para verificar la calidad del código
      - name: Linting con Ruff
        run: ruff check . --fix

      # 5. Verifica que el código esté formateado correctamente con Black
      - name: Formateo con Black
        run: black --check .

      - name: Crear directorio de logs
        run: mkdir -p logs

       # 6. Ejecutar test con pytest
      - name: Ejecutar Pruebas
        # Aquí inyectamos las variables de entorno para el CI
        env:
          ALLOWED_HOSTS: 'localhost,127.0.0.1'
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG: 'True'
          DB_ENGINE: 'django.db.backends.sqlite3'
          DB_NAME: ':memory:'
          DJANGO_SETTINGS_MODULE: 'config.settings'

        run: |
            pytest -v --cov=apps/usuarios --cov-report=term-missing