# Nombre del workflow que aparecerá en la pestaña "Actions" de GitHub
name: CI de Django

# Define cuándo se debe ejecutar este workflow
on:
  # Se ejecuta en cada push a la rama "main"
  push:
    branches: [ "main" ]
  # También se ejecuta en cada Pull Request que apunte a la rama "main"
  pull_request:
    branches: [ "main" ]

# Define los trabajos (jobs) que se ejecutarán
jobs:
  # Nombre del trabajo, puedes llamarlo como quieras (ej. "build", "test")
  build:
    # El tipo de máquina virtual donde se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Los pasos que componen el trabajo
    steps:
      # 1. Clona tu repositorio en la máquina virtual
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configura el entorno de Python
      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # Habilita el caché para las dependencias de pip para acelerar futuras ejecuciones
          cache: 'pip'

      # 3. Instala las dependencias del proyecto
      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Instala ruff y black si no están en requirements.txt
          pip install ruff black

      # 4. Ejecuta el linter para verificar la calidad del código
      - name: Linting con Ruff
        run: ruff check . --fix

      # 5. Verifica que el código esté formateado correctamente con Black
      - name: Formateo con Black
        run: black --check .

       # 6. Ejecuta las pruebas automatizadas de Django
      - name: Ejecutar Pruebas
        # Aquí inyectamos las variables de entorno para el CI
        env:
          # Usa el secreto que creaste en GitHub
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG: 'True'
          # Sobrescribe la configuración de la DB para usar SQLite en memoria
          DB_ENGINE: 'django.db.backends.sqlite3'
          DB_NAME: ':memory:'
        
        run: python manage.py test